--物品

local mod = Isaac_BenightedSoul

local function Load(fileName)
	return include('ibs_scripts.items.items.'..fileName)
end

--道具
mod.IBS_Item = {
	LightD6 = Load('light_d6'),
	NoOptions = Load('no_options'),
	D4D = Load('d4d'),
	SSG = Load('shooting_stars_gazer'),
	Waster = Load('waster'),
	Envy = Load('envy'),
	GlowingHeart = Load('glowing_heart'),
	PurpleBubbles = Load('purple_bubbles'),
	CursedMantle = Load('cursed_mantle'),
	Hypercube = Load('hypercube'),
	Defined = Load('defined'),
	Chocolate = Load('chocolate'),
	Diamoond = Load('diamoond'),
	Cranium = Load('cranium'),
	Ether = Load('ether'),
	Wisper = Load('wisper'),
	BOT = Load('bone_of_temperance'),
	GOF = Load('guard_of_fortitude'),
	V7 = Load('v7'),
	TGOJ = Load('the_gospel_of_judas'),
	ReservedNail = Load('reserved_nail'),
	SuperB = Load('superb'),
	DreggyPie = Load('dreggy_pie'),
	BonyKnife = Load('bony_knife'),
	Circumcision = Load('circumcision'),
	CursedHeart = Load('cursed_heart'),
	Redeath = Load('redeath'),
	DustyBomb = Load('dusty_bomb'),
	NeedleMushroom = Load('needle_mushroom'),
	MiniHorn = Load('mini_horn'),
	WOA = Load('wings_of_apollyon'),
	MomsCheque = Load('moms_cheque'),
	ForbiddenFruit = Load('forbidden_fruit'),
	Sword = Load('sword'),
	Regret = Load('regret'),
	Sacrifice = Load('sacrifice'),
	Sacrifice2 = Load('sacrifice2'),
	Multiplication = Load('multiplication'),
	NoTemperance = Load('no_temperance'),
	GuppysPotty = Load('guppys_potty'),
	LOL = Load('lord_of_locusts'),
	Falowerse = Load('falowerse'),
	FalsehoodOfXXX = Load('falsehood_bxxx'),
	GoldExperience = Load('gold_experience'),
	ChubbyCookbook = Load('chubby_cookbook'),
	ProfaneWeapon = Load('profane_weapon'),
	RulesBook = Load('rules_book'),
	CathedralWindow = Load('cathedral_window'),
	LeadenHeart = Load('leaden_heart'),
	China = Load('china'),
	SilverBracelet = Load('silver_bracelet'),
	ROH = Load('route_of_humility'),
	Tenebrosity = Load('tenebrosity'),
	HellKitchen = Load('hell_kitchen'),
	StolenDecade = Load('stolen_decade'),
	DiceProjector = Load('dice_projector'),
	Hoarding = Load('hoarding'),
	SuperPanicButton = Load('super_panic_button'),
	Blackjack = Load('blackjack'),
	Sketch = Load('sketch'),
	Molekale = Load('molekale'),
	Ssstew = Load('ssstew'),
	BookOfSeen = Load('book_of_seen'),
	PortableFarm = Load('portable_farm'),
	GrowingWheatI = Load('wheat_stage1'),
	GrowingWheatI = Load('wheat_stage1'),
	GrowingWheatII = Load('wheat_stage2'),
	GrowingWheatIII = Load('wheat_stage3'),
	GrowingWheatIV = Load('wheat_stage4'),
	GrowingWheatV = Load('wheat_stage5'),
	GrowingWheatVI = Load('wheat_stage6'),
	Wheat = Load('wheat'),
	Bread = Load('bread'),
	Goatify = Load('goatify'),
	ElegiastWinter = Load('elegiast_winter'),
	GHD = Load('ghd'),
	Grail = Load('grail'),
	Moth = Load('moth'),
	Edge = Load('edge'),
	Edge2 = Load('edge2'),
	Edge3 = Load('edge3'),
	Forge = Load('forge'),
	SecretHistories = Load('secret_histories'),
	AnotherKarma = Load('another_karma'),
	Alms = Load('alms'),
	NotchedSword = Load('notched_sword'),
	Troposphere = Load('troposphere'),
	MODE = Load('model_of_deligence'),
	LODI = Load('lamp_of_diligence'),
	ContactC = Load('contact_c'),
	MaxxC = Load('maxx_c'),
	Multiply = Load('multiply'),
	SCP018 = Load('018'),
	SneakyC = Load('sneaky_c'),
	ConfrontingC = Load('confronting_c'),
	RetaliatingC = Load('retaliating_c'),
	MasterRound = Load('master_round'),
	MasterPack = Load('master_pack'),
	RichMines = Load('rich_mines'),
	Panacea = Load('panacea'),
	SmileWorld = Load('smile_world'),
	FGHD = Load('false_ghd'),
	SOG = Load('generosity_soul'),
	Clash = Load('clash'),
	TheBestWeapon = Load('the_best_weapon'),
	ThreeWishes = Load('three_wishes'),
	ChestChest = Load('chest_chest'),
	CheeseCutter = Load('cheese_cutter'),
	Turbo = Load('turbo'),
	TreasureKey = Load('treasure_key'),
	AKEY47 = Load('akey47'),
	SilverKey = Load('the_silver_key'),
	TruthChest = Load('truth_chest'),
	Knock = Load('knock'),
	WilderingMirror = Load('wildering_mirror'),
	WilderingMirror2 = Load('wildering_mirror2'),
	MoonStreets = Load('moon_streets'),
	Fomalhaut = Load('fomalhaut'),
	LuckEnchantment = Load('luck_enchantment'),
	TheHornedAxe = Load('the_horned_axe'),
	LightBarrier = Load('light_barrier'),
	ChillMind = Load('chill_mind'),
	LownTea = Load('lown_tea'),
	TheEyeofTruth = Load('the_eye_of_truth'),
	Turbine = Load('turbine'),
	RedHook = Load('red_hook'),
	OvO = Load('ovo'),
	DanishGambit = Load('danish_gambit'),
	HyperBlock = Load('hyper_block'),
	FusionHammer = Load('fusion_hammer'),
	SangenSummoning = Load('sangen_summoning'),
	PeacePipe = Load('peace_pipe'),
	Yongle = Load('yongle'),
	HexaVessel = Load('hexa_vessel'),
	Flex = Load('flex'),
	SignatureMove = Load('signature_move'),
	DoubleDosage = Load('double_dosage'),
	HolyInjection = Load('holy_injection'),
	KilleR = Load('kille_r'),
	VeinMiner = Load('vein_miner'),
	VainMiner = Load('vain_miner'),
	PUC = Load('puc'),
	SaleBomb = Load('sale_bomb'),
	Diecry = Load('diecry'),
	ReusedStory = Load('reused_story'),
	Zoth = Load('zoth'),
	PageantFather = Load('pageant_father'),
	DeciduousMeat = Load('deciduous_meat'),
	CurseSyringe = Load('curse_syringe'),
	AstroVera = Load('astro_vera'),
	CurseoftheFool = Load('curse_of_the_fool'),
	UnburntGod = Load('burning_of_unburnt_god'),

}

local function Load(fileName)
	return include('ibs_scripts.items.trinkets.'..fileName)
end

--饰品
mod.IBS_Trinket = {
	BottleShard = Load('bottle_shard'),
	DadsPromise = Load('dads_promise'),
	GamblersEye = Load('gamblers_eye'),
	BaconSaver = Load('bacon_saver'),
	DivineRetaliation = Load('divine_retaliation'),
	ToughHeart = Load('tough_heart'),
	ChaoticBelief = Load('chaotic_belief'),
	ThronyRing = Load('throny_ring'),
	PresentationalMind = Load('presentational_mind'),
	Export = Load('export'),
	Nemesis = Load('nemesis'),
	Barren = Load('barren'),
	LeftFoot = Load('left_foot'),
	RabbitHead = Load('rabbit_head'),
	LunarTwigs = Load('lunar_twigs'),
	Interval = Load('interval'),
	NumeronForce = Load('numeron_force'),
	WheatSeeds = Load('wheat_seeds'),
	CorruptedDeck = Load('corrupted_deck'),
	GlitchedPenny = Load('glitched_penny'),
	StarryPenny = Load('starry_penny'),
	PaperPenny = Load('paper_penny'),
	CultistMask = Load('cultist_mask'),
	SsserpentHead = Load('ssserpent_head'),
	ClericFace = Load('cleric_face'),
	NlothsMask = Load('nloths_mask'),
	GremlinMask = Load('gremlin_mask'),
	OldPenny = Load('old_penny'),
	CrackCallback = Load('crack_callback'),
	Foe = Load('foe'),
	OddKey = Load('odd_key'),
	Neopolitan = Load('neopolitan'),
	WildMilk = Load('wild_milk'),
	BlackCharm = Load('black_charm'),
	WarHospital = Load('war_hospital'),
	SporeCloud = Load('spore_cloud'),
	ForScreenshot = Load('for_screenshot'),
		
}

local function Load(fileName)
	return include('ibs_scripts.items.pockets.'..fileName)
end

--口袋物品
mod.IBS_Pocket = {
	CuZnD6 = Load('czd6'),
	GoldenPrayer = Load('golden_prayer'),
	StolenYear = Load('stolen_year'),
	NeniaDea = Load('nenia_dea'),

	--伪忆
	BIsaac = Load('falsehoods.falsehood_bisaac'),
	BMaggy = Load('falsehoods.falsehood_bmaggy'),
	BCain = Load('falsehoods.falsehood_bcain'),
	BAbel = Load('falsehoods.falsehood_babel'),
	BJudas = Load('falsehoods.falsehood_bjudas'),
	BEve = Load('falsehoods.falsehood_beve'),
	BSamson = Load('falsehoods.falsehood_bsamson'),
	BAzazel = Load('falsehoods.falsehood_bazazel'),
	BLazarus = Load('falsehoods.falsehood_blazarus'),
	BEden = Load('falsehoods.falsehood_beden'),
	BLost = Load('falsehoods.falsehood_blost'),
	BLilith = Load('falsehoods.falsehood_blilith'),
	BKeeper = Load('falsehoods.falsehood_bkeeper'),
	BApollyon = Load('falsehoods.falsehood_bapollyon'),
	BForgotten = Load('falsehoods.falsehood_bforgotten'),
	BBeth = Load('falsehoods.falsehood_bbeth'),
	BJBE = Load('falsehoods.falsehood_bjbe'),
}


